### ISSUE TITLE
Export more arbiter data, append the optional flag –arbiter-data appears to fail

### ISSUE THREAD

**Issue by victor-zheng-codes** [erral/fideparser#5]
`export_fide_tournaments ESP 2013-01-01 2013-january-spain.csv csv --arbiter-data` causes the following error

![image](https://github.com/erral/fideparser/assets/52824986/ff21859f-b9ca-4743-9787-f57b176dffa0)

**Comment by erral** [comment]
Thanks, FIDE changed the HTML the script was prepared for the old site. I have updated it for the new HTML.
